name: mychild
description: "My Child – Learn, Speak & Grow (App éducative)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/france.png
    - assets/anglais.jpeg
    - assets/sounds/fr/
    - assets/sounds/en/
